#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : eventlet
Version  : 0.26.1
Release  : 54
URL      : https://files.pythonhosted.org/packages/db/eb/c2723931f0216cc4acef598393e352edc725089b68cf508a842ad746173c/eventlet-0.26.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/db/eb/c2723931f0216cc4acef598393e352edc725089b68cf508a842ad746173c/eventlet-0.26.1.tar.gz
Summary  : Highly concurrent networking library
Group    : Development/Tools
License  : MIT
Requires: eventlet-license = %{version}-%{release}
Requires: eventlet-python = %{version}-%{release}
Requires: eventlet-python3 = %{version}-%{release}
Requires: dnspython
Requires: greenlet
Requires: monotonic
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : dnspython
BuildRequires : greenlet
BuildRequires : greenlet-python
BuildRequires : monotonic
BuildRequires : nose
BuildRequires : nose-python
BuildRequires : six

%description
It uses epoll or libevent for highly scalable non-blocking I/O.  Coroutines ensure that the developer uses a blocking style of programming that is similar to threading, but provide the benefits of non-blocking I/O.  The event dispatch is implicit, which means you can easily use Eventlet from the Python interpreter, or as a small part of a larger application.
        
        It's easy to get started using Eventlet, and easy to convert existing
        applications to use it.  Start off by looking at the `examples`_,
        `common design patterns`_, and the list of `basic API primitives`_.

%package license
Summary: license components for the eventlet package.
Group: Default

%description license
license components for the eventlet package.


%package python
Summary: python components for the eventlet package.
Group: Default
Requires: eventlet-python3 = %{version}-%{release}

%description python
python components for the eventlet package.


%package python3
Summary: python3 components for the eventlet package.
Group: Default
Requires: python3-core
Provides: pypi(eventlet)
Requires: pypi(dnspython)
Requires: pypi(greenlet)
Requires: pypi(monotonic)
Requires: pypi(six)

%description python3
python3 components for the eventlet package.


%prep
%setup -q -n eventlet-0.26.1
cd %{_builddir}/eventlet-0.26.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1596151356
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/eventlet
cp %{_builddir}/eventlet-0.26.1/LICENSE %{buildroot}/usr/share/package-licenses/eventlet/ad33faded4baaba18a31704973874c531e94d910
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/eventlet/ad33faded4baaba18a31704973874c531e94d910

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
